-- created by jxiao
-- replaced with xp_smtp_sendmail, jx

if exists (select * from sysobjects where name = 'trigger_merged_orders' and type = 'tr')
  drop trigger trigger_merged_orders
go

create trigger trigger_merged_orders
on orders
for update
as     
    declare @s1 varchar(10)
    declare @s2 varchar(10) 
    declare @t1 money
    declare @t2 money 
    declare @order_number float
    declare @body_message varchar(30)
  if update(stage)
    begin
      set nocount on
      select @s1 = d.stage, @s2 = i.stage, @order_number = d.order_number
      from deleted d, inserted i 
      where d.order_number = i.order_number
      set @body_message = 'for order ' + ltrim(str(@order_number,10,2)) 
                   --3rd param changed to 2 from 1, so that .00999 will be converted to 0.01, jx
      if @s1 in ('completed','invoice') and @s2 = 'shippaper'
          begin 
			exec master.dbo.xp_smtp_sendmail 
					@from = 'jackxiao11@yahoo.com',
					@to = 'jackxiao11@yahoo.com',
	                @subject = 'Merged order happens (stage)',
	                @message = @body_message,
					@server = '172.16.2.190'
          insert into temp_orders 
(  ORDER_NUMBER,  ORG_CODE,  ORDER_TYPE_CODE,  STAGE,  SOURCE_SYSTEM,  
BATCH_NUM,  HOLD_CODE,  ORDER_DATE,  BT_ID,  ST_ID,  ENTERED_DATE_TIME,  ENTERED_BY,
  UPDATED_DATE_TIME,UPDATED_BY,
  NUMBER_LINES,  FULL_NAME,  COMPANY,  ADDRESS_1,  ADDRESS_2,  CITY,  
STATE_PROVINCE,  ZIP,  COUNTRY,  PHONE,  TOTAL_CHARGES,  TOTAL_PAYMENTS,  BALANCE,    
LINE_TOTAL,  LINE_TAXABLE,  FREIGHT_1,  HANDLING_1,  TAX_1,  LINE_PAY,  OTHER_PAY,  AR_PAY,  
TAX_AUTHOR_1,  TAX_RATE_1,  TAX_EXEMPT,  TERMS_CODE,  SCHEDULED_DATE,  SOURCE_CODE,  
DISCOUNT_RATE,  PRIORITY,  HOLD_COMMENT,  AFFECT_INVENTORY,  HOLD_FLAG,   CUSTOMER_REFERENCE,  
UNDISCOUNTED_TOTAL,  BACKORDERS,  MEMBER_TYPE,  PAY_TYPE,  PAY_NUMBER,  CREDIT_CARD_EXPIRES,  
AUTHORIZE,  CREDIT_CARD_NAME,  BO_STATUS,  BO_RELEASE_DATE,SHIP_METHOD,  TOTAL_WEIGHT,  
CASH_GL_ACCT,  LINE_PST_TAXABLE,  INTENT_TO_EDIT,  PREPAID_INVOICE_REFERENCE_NUM,INVOICE_REFERENCE_NUM, INVOICE_NUMBER, 
AUTO_CALC_FREIGHT,  CO_ID,    CO_MEMBER_TYPE,  EMAIL,  FAX,LAST_FIRST,COMPANY_SORT,IS_FR_ORDER)   
select 
ORDER_NUMBER,  ORG_CODE,  ORDER_TYPE_CODE,  STAGE,  SOURCE_SYSTEM,  
BATCH_NUM,  HOLD_CODE,  ORDER_DATE,  BT_ID,  ST_ID,  ENTERED_DATE_TIME,  ENTERED_BY,
  UPDATED_DATE_TIME,UPDATED_BY,
  NUMBER_LINES,  FULL_NAME,  COMPANY,  ADDRESS_1,  ADDRESS_2,  CITY,  
STATE_PROVINCE,  ZIP,  COUNTRY,  PHONE,  TOTAL_CHARGES,  TOTAL_PAYMENTS,  BALANCE,    
LINE_TOTAL,  LINE_TAXABLE,  FREIGHT_1,  HANDLING_1,  TAX_1,  LINE_PAY,  OTHER_PAY,  AR_PAY,  
TAX_AUTHOR_1,  TAX_RATE_1,  TAX_EXEMPT,  TERMS_CODE,  SCHEDULED_DATE,  SOURCE_CODE,  
DISCOUNT_RATE,  PRIORITY,  HOLD_COMMENT,  AFFECT_INVENTORY,  HOLD_FLAG,   CUSTOMER_REFERENCE,  
UNDISCOUNTED_TOTAL,  BACKORDERS,  MEMBER_TYPE,  PAY_TYPE,  PAY_NUMBER,  CREDIT_CARD_EXPIRES,  
AUTHORIZE,  CREDIT_CARD_NAME,  BO_STATUS,  BO_RELEASE_DATE,SHIP_METHOD,  TOTAL_WEIGHT,  
CASH_GL_ACCT,  LINE_PST_TAXABLE,  INTENT_TO_EDIT,  PREPAID_INVOICE_REFERENCE_NUM,INVOICE_REFERENCE_NUM, INVOICE_NUMBER, 
AUTO_CALC_FREIGHT,  CO_ID,    CO_MEMBER_TYPE,  EMAIL,  FAX,LAST_FIRST,COMPANY_SORT,IS_FR_ORDER  
from deleted where order_number = @order_number
union
select 
ORDER_NUMBER,  ORG_CODE,  ORDER_TYPE_CODE,  STAGE,  SOURCE_SYSTEM,  
BATCH_NUM,  HOLD_CODE,  ORDER_DATE,  BT_ID,  ST_ID,  ENTERED_DATE_TIME,  ENTERED_BY,
  UPDATED_DATE_TIME,UPDATED_BY,
  NUMBER_LINES,  FULL_NAME,  COMPANY,  ADDRESS_1,  ADDRESS_2,  CITY,  
STATE_PROVINCE,  ZIP,  COUNTRY,  PHONE,  TOTAL_CHARGES,  TOTAL_PAYMENTS,  BALANCE,    
LINE_TOTAL,  LINE_TAXABLE,  FREIGHT_1,  HANDLING_1,  TAX_1,  LINE_PAY,  OTHER_PAY,  AR_PAY,  
TAX_AUTHOR_1,  TAX_RATE_1,  TAX_EXEMPT,  TERMS_CODE,  SCHEDULED_DATE,  SOURCE_CODE,  
DISCOUNT_RATE,  PRIORITY,  HOLD_COMMENT,  AFFECT_INVENTORY,  HOLD_FLAG,   CUSTOMER_REFERENCE,  
UNDISCOUNTED_TOTAL,  BACKORDERS,  MEMBER_TYPE,  PAY_TYPE,  PAY_NUMBER,  CREDIT_CARD_EXPIRES,  
AUTHORIZE,  CREDIT_CARD_NAME,  BO_STATUS,  BO_RELEASE_DATE,SHIP_METHOD,  TOTAL_WEIGHT,  
CASH_GL_ACCT,  LINE_PST_TAXABLE,  INTENT_TO_EDIT,  PREPAID_INVOICE_REFERENCE_NUM,INVOICE_REFERENCE_NUM, INVOICE_NUMBER, 
AUTO_CALC_FREIGHT,  CO_ID,    CO_MEMBER_TYPE,  EMAIL,  FAX,LAST_FIRST,COMPANY_SORT,IS_FR_ORDER  
from inserted where order_number = @order_number
          end
    end

-- for update trigger to track the total_charges change in orders
  if update(total_charges)
    begin
      set nocount on
      select @t1 = d.total_charges, @t2 = i.total_charges, @order_number = d.order_number,
            @s1 = d.stage
      from deleted d, inserted i 
      where d.order_number = i.order_number
        and d.order_type_code in ('return', 'credit', 'reg')
        and i.order_type_code in ('return', 'credit', 'reg')
      set @body_message = 'for order ' + ltrim(str(@order_number,10,2))
      if @s1 in ('completed','invoice') and @t2 <> @t1 and @t2 <> 0 and abs(@t2-@t1) > 0.1
          begin
          insert into temp_orders 
(  ORDER_NUMBER,  ORG_CODE,  ORDER_TYPE_CODE,  STAGE,  SOURCE_SYSTEM,  
BATCH_NUM,  HOLD_CODE,  ORDER_DATE,  BT_ID,  ST_ID,  ENTERED_DATE_TIME,  ENTERED_BY,
  UPDATED_DATE_TIME,UPDATED_BY,
  NUMBER_LINES,  FULL_NAME,  COMPANY,  ADDRESS_1,  ADDRESS_2,  CITY,  
STATE_PROVINCE,  ZIP,  COUNTRY,  PHONE,  TOTAL_CHARGES,  TOTAL_PAYMENTS,  BALANCE,    
LINE_TOTAL,  LINE_TAXABLE,  FREIGHT_1,  HANDLING_1,  TAX_1,  LINE_PAY,  OTHER_PAY,  AR_PAY,  
TAX_AUTHOR_1,  TAX_RATE_1,  TAX_EXEMPT,  TERMS_CODE,  SCHEDULED_DATE,  SOURCE_CODE,  
DISCOUNT_RATE,  PRIORITY,  HOLD_COMMENT,  AFFECT_INVENTORY,  HOLD_FLAG,   CUSTOMER_REFERENCE,  
UNDISCOUNTED_TOTAL,  BACKORDERS,  MEMBER_TYPE,  PAY_TYPE,  PAY_NUMBER,  CREDIT_CARD_EXPIRES,  
AUTHORIZE,  CREDIT_CARD_NAME,  BO_STATUS,  BO_RELEASE_DATE,SHIP_METHOD,  TOTAL_WEIGHT,  
CASH_GL_ACCT,  LINE_PST_TAXABLE,  INTENT_TO_EDIT,  PREPAID_INVOICE_REFERENCE_NUM,INVOICE_REFERENCE_NUM, INVOICE_NUMBER, 
AUTO_CALC_FREIGHT,  CO_ID,    CO_MEMBER_TYPE,  EMAIL,  FAX,LAST_FIRST,COMPANY_SORT,IS_FR_ORDER)   
select 
ORDER_NUMBER,  ORG_CODE,  ORDER_TYPE_CODE,  STAGE,  SOURCE_SYSTEM,  
BATCH_NUM,  HOLD_CODE,  ORDER_DATE,  BT_ID,  ST_ID,  ENTERED_DATE_TIME,  ENTERED_BY,
  UPDATED_DATE_TIME,UPDATED_BY,
  NUMBER_LINES,  FULL_NAME,  COMPANY,  ADDRESS_1,  ADDRESS_2,  CITY,  
STATE_PROVINCE,  ZIP,  COUNTRY,  PHONE,  TOTAL_CHARGES,  TOTAL_PAYMENTS,  BALANCE,    
LINE_TOTAL,  LINE_TAXABLE,  FREIGHT_1,  HANDLING_1,  TAX_1,  LINE_PAY,  OTHER_PAY,  AR_PAY,  
TAX_AUTHOR_1,  TAX_RATE_1,  TAX_EXEMPT,  TERMS_CODE,  SCHEDULED_DATE,  SOURCE_CODE,  
DISCOUNT_RATE,  PRIORITY,  HOLD_COMMENT,  AFFECT_INVENTORY,  HOLD_FLAG,   CUSTOMER_REFERENCE,  
UNDISCOUNTED_TOTAL,  BACKORDERS,  MEMBER_TYPE,  PAY_TYPE,  PAY_NUMBER,  CREDIT_CARD_EXPIRES,  
AUTHORIZE,  CREDIT_CARD_NAME,  BO_STATUS,  BO_RELEASE_DATE,SHIP_METHOD,  TOTAL_WEIGHT,  
CASH_GL_ACCT,  LINE_PST_TAXABLE,  INTENT_TO_EDIT,  PREPAID_INVOICE_REFERENCE_NUM,INVOICE_REFERENCE_NUM, INVOICE_NUMBER, 
AUTO_CALC_FREIGHT,  CO_ID,    CO_MEMBER_TYPE,  EMAIL,  FAX,LAST_FIRST,COMPANY_SORT,IS_FR_ORDER  
from deleted where order_number = @order_number
union
select 
ORDER_NUMBER,  ORG_CODE,  ORDER_TYPE_CODE,  STAGE,  SOURCE_SYSTEM,  
BATCH_NUM,  HOLD_CODE,  ORDER_DATE,  BT_ID,  ST_ID,  ENTERED_DATE_TIME,  ENTERED_BY,
  UPDATED_DATE_TIME,UPDATED_BY,
  NUMBER_LINES,  FULL_NAME,  COMPANY,  ADDRESS_1,  ADDRESS_2,  CITY,  
STATE_PROVINCE,  ZIP,  COUNTRY,  PHONE,  TOTAL_CHARGES,  TOTAL_PAYMENTS,  BALANCE,    
LINE_TOTAL,  LINE_TAXABLE,  FREIGHT_1,  HANDLING_1,  TAX_1,  LINE_PAY,  OTHER_PAY,  AR_PAY,  
TAX_AUTHOR_1,  TAX_RATE_1,  TAX_EXEMPT,  TERMS_CODE,  SCHEDULED_DATE,  SOURCE_CODE,  
DISCOUNT_RATE,  PRIORITY,  HOLD_COMMENT,  AFFECT_INVENTORY,  HOLD_FLAG,   CUSTOMER_REFERENCE,  
UNDISCOUNTED_TOTAL,  BACKORDERS,  MEMBER_TYPE,  PAY_TYPE,  PAY_NUMBER,  CREDIT_CARD_EXPIRES,  
AUTHORIZE,  CREDIT_CARD_NAME,  BO_STATUS,  BO_RELEASE_DATE,SHIP_METHOD,  TOTAL_WEIGHT,  
CASH_GL_ACCT,  LINE_PST_TAXABLE,  INTENT_TO_EDIT,  PREPAID_INVOICE_REFERENCE_NUM,INVOICE_REFERENCE_NUM, INVOICE_NUMBER, 
AUTO_CALC_FREIGHT,  CO_ID,    CO_MEMBER_TYPE,  EMAIL,  FAX,LAST_FIRST,COMPANY_SORT,IS_FR_ORDER  
from inserted where order_number = @order_number
          end
    end
go
